sheet_patterns:
  - "*NB_Standortinformation*"
  - "*NB_Standortinformation*"
  - "*NB_Standortinformation*"

verpflegung_structure:
  "Verpflegung:":
    - "Verpflegung Halbtagsbetreuung"
    - "Verpflegung Teilzeitbetreuung"
    - "Verpflegung Ganztagsbetreuung"

zusatzleistungen_structure:
  "Zusatzleistungen":
    - "Zusatzleistung 1"
    - "Zusatzleistung 2"
    - "Zusatzleistung 3"
    - "Zusatzleistung 4"
    - "Zusatzleistung 5"

section_markers:
  - "KINDERGÄRTEN UND KINDERGRUPPEN"
  - "Einmalzahlungen" 