sheet_patterns:
  - "NB_Standortinformation"
  - "*NB_Standortinformation*"


verpflegung_structure:
  "Verpflegung:":
    - "Verpflegung Halbtagsbetreuung"
    - "Verpflegung Teilzeitbetreuung"
    - "Verpflegung Ganztagsbetreuung"

zusatzleistungen_structure:
  "Zusatzleistungen":
    - "Montessori"
    - "Englisch"
    - "Musik"
    - "erhöhter Betreuungsschlüssel"


section_markers:
  - "KINDERGÄRTEN UND KINDERGRUPPEN"
  - "Einmalzahlungen" 