II. KOSTENZUSCHÜSSE DER MA 10:
II. KOSTENZUSCHÜSSE DER MA 10
    description: MA 10 cost subsidies
    items:
      - Kinder 0-6 Jahre (Betreuungsbeitrag und Grundbeitrag)
      - Verwaltungszuschuss
      - Zuschüsse aus der Anstoßfinanzierung
      - noch zu verbrauchende Zuschüsse aus der Anstoßfinanzierung
      - Sonderfinanzierung Teuerung
      - Energiekostenzuschuss
      - Sonderförderung MA 10 für zusätzliche Assistent*innen in Kindergartengruppen
      - Kostenzuschüsse MA 10 für heilpädagogische Kinder
      - Kostenzuschüsse der MA 10 für Integrationsgruppen
      - Corona-Platz-Sicherungsbeitrag