# Configuration for material expenses (Sachausgaben) data extraction
sheet_patterns:
  - "NB_KIGA"
  - "NB_KKG"

# Section identifier
section_id: "II. SACHAUSGABEN"

# Output column configuration
output_columns:
  - source_file
  - category
  - subcategory
  - subcategory_desc
  - detail
  - value_2022
  - value_2023
  - comment

# Categories and their items
categories:
  "1. INFRASTRUKTURAUSGABEN":
    description: "Infrastructure expenses"
    items:
      - "Energie (Gas/Strom), Wasser"
      - "Miete und Betriebskosten"
      - "Telefon/Internet"
      - "Geringwertige Wirtschaftsgüter (Anschaffungswert < € 1.000)"
      - "Instandhaltung und Reparaturen"
      - "Ausgaben im Rahmen der Anstoßfinanzierung"
      - "Garten und Dekoration"
      - "sonstige Infrastrukturausgaben"
  
  "2. VERWALTUNGSAUSGABEN":
    description: "Administrative expenses"
    items:
      - "Rechts- und Steuerberatung"
      - "Buchhaltung, Lohnverrechnung"
      - "Büromaterial und Fotokopien"
      - "Porto"
      - "Geldverkehrspesen (ohne Kreditrückzahlungen)"
      - "Infrastrukturausgaben für Zentralverwaltung"
      - "sonstige Verwaltungsausgaben"
  
  "3. ALLGEMEINE AUSGABEN":
    description: "General expenses"
    items:
      - "Reinigungsmaterial"
      - "Versicherungsprämien"
      - "Zinsen für Darlehen"
      - "Gebühren und Abgaben"
      - "weitere allgemeine Ausgaben (bitte einzeln auflisten!)"
  
  "4. BETREUUNGSAUSGABEN":
    description: "Care expenses"
    items:
      - "Ausgaben für Verpflegung"
      - "Spielgeräte und Spiele"
      - "Material für Bastelarbeiten"
      - "Medikamente/Apotheke, Hygieneartikel der Kinderbetreuung (z.B. Windeln, Puder, uä)"
      - "Fahrtkosten, Ausflüge"
      - "weitere Betreuungsausgaben (bitte einzeln auflisten!)"
  
  "5. KFZ-AUSGABEN":
    description: "Vehicle expenses"
    items:
      - "KFZ-Leasing"
      - "KFZ-Versicherung"
      - "Ausgaben für Service und Reparatur"
      - "Ausgaben für Treibstoff"
      - "Verrechnetes Kilometergeld"
      - "sonstige KFZ-Ausgaben"
  
  "6. SACHAUSGABEN FÜR ZUSATZLEISTUNGEN":
    description: "Material expenses for additional services"
    items:
      - "Sachausgaben zur ausschließlichen Erfüllung der Zusatzleistungen"
  
  "7. ABSCHREIBUNGEN":
    description: "Depreciation"
    items:
      - "Abschreibungen" 