Vermögen:
  items:
    - "Betriebsausstattung (Buchwert) 1)"
    - "Sparguthaben Erste"
    - "Kassabestand"
    - "Bank Erste AT592011128956917700"
    - "Guthaben Konto Nr. XXXXXXX (Kontostand) 2)"
    - "geleistete Anzahlungen"
    - "ausstehende Elternbeiträge"
    - "offene Förderbeiträge"
    - "sonstige Forderungen"
    - "freies Feld 4)"
    - "freies Feld 4)"