# Configuration for Verpflegung (catering) data extraction

# Patterns to identify the correct sheet
sheet_patterns:
  - "NB_VERPFLEGUNG"

# Section marker to find the start of the data
section_marker: "NB_VERPFLEGUNG"

# Output columns in the desired order
output_columns:
  - "category"
  - "year_x"
  - "year_y"
  - "source_file"

# Main section structure - list of expected rows to extract
verpflegung_rows:
  - "Selbstkocher"
  - "Einnahmen aus Elternbeiträgen (ohne Hort)"
  - "Ausgaben für Nahrungsmittel (ohne Hort)"
  - "sonstige Ausgaben (ohne Hort) für Verpflegung:"
  - "Koch/Köchin 1)"
  - "weitere anrechenbare Ausgaben 2)"
  - "Summe"
  - "Differenz in EUR"
  - "Deckung der Ausgaben durch Elternbeiträge 3)"

# Special handling flags
boolean_fields:
  - "Selbstkocher"

numeric_fields:
  - "Einnahmen aus Elternbeiträgen (ohne Hort)"
  - "Ausgaben für Nahrungsmittel (ohne Hort)"
  - "Koch/Köchin 1)"
  - "weitere anrechenbare Ausgaben 2)"
  - "Summe"
  - "Differenz in EUR"
  - "Deckung der Ausgaben durch Elternbeiträge 3)" 