- Selbstkocher
- "Einnahmen aus Elternbeiträgen (ohne Hort)"
- "Ausgaben für Nahrungsmittel (ohne Hort)"
- "sonstige Ausgaben (ohne Hort) für Verpflegung:"
- "Koch/Köchin 1)"
- "weitere anrechenbare Ausgaben 2)"
- Summe
- "Differenz in EUR"
- "Deckung der Ausgaben durch Elternbeiträge 3)"